# common.sh: Shared shell configuration for both POSIX (Bash/Zsh) shells
# Note: This file is sourced by dot_bashrc.tmpl and dot_zshrc.tmpl.

# Ensure ~/.local/bin is in PATH for user-installed binaries (like pip packages or custom tools)
if [ -d "$HOME/.local/bin" ] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

# Load centralized environment variables
if [ -f "$HOME/.config/shell/env.list" ]; then
  # Ignore empty lines and lines starting with '#'
  while IFS='=' read -r key value; do
    if [ -n "$key" ] && [[ "$key" != \#* ]]; then
      export "$key=$value"
    fi
  done < "$HOME/.config/shell/env.list"
fi

# Load centralized aliases (generated by chezmoi)
[ -f "$HOME/.config/shell/aliases.sh" ] && . "$HOME/.config/shell/aliases.sh"

# Fix colors inside tmux sessions
if [ -n "$TMUX" ]; then
  export TERM="screen-256color"
fi

# Utility: Create a directory and immediately `cd` into it
mkd() {
  mkdir -p "$1" && cd "$1"
}
