# common.sh: Shared shell configuration for both POSIX (Bash/Zsh) shells
# Note: This file is sourced by dot_bashrc.tmpl and dot_zshrc.tmpl.

# Ensure ~/.local/bin is in PATH for user-installed binaries (like pip packages or custom tools)
if [ -d "$HOME/.local/bin" ] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

# Load centralized environment variables
if [ -f "$HOME/.config/shell/env.list" ]; then
  # Ignore empty lines and lines starting with '#'
  while IFS='=' read -r key value; do
    if [ -n "$key" ] && [[ "$key" != \#* ]]; then
      export "$key=$value"
    fi
  done < "$HOME/.config/shell/env.list"
fi

# Load centralized aliases (generated by chezmoi)
[ -f "$HOME/.config/shell/aliases.sh" ] && . "$HOME/.config/shell/aliases.sh"

# Fix colors inside tmux sessions
if [ -n "$TMUX" ]; then
  export TERM="screen-256color"
fi

# Utility: Create a directory and immediately `cd` into it
mkd() {
  if [ $# -lt 1 ] || [ -z "${1:-}" ]; then
    printf 'usage: mkd <dir>\n' >&2
    return 1
  fi
  mkdir -p "$1" && cd "$1"
}

# Docker helpers for working with containers by short ID or name
dpsg() {
  if [ $# -gt 0 ] && [ -n "${1:-}" ]; then
    docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Ports}}\t{{.Image}}\t{{.Status}}' | grep -i "$1"
  else
    docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Ports}}\t{{.Image}}\t{{.Status}}'
  fi
}

dlog() {
  if [ $# -lt 1 ] || [ -z "${1:-}" ]; then
    printf 'usage: dlog <container>\n' >&2
    return 1
  fi
  docker logs -f "$1"
}

dsh() {
  if [ $# -lt 1 ] || [ -z "${1:-}" ]; then
    printf 'usage: dsh <container>\n' >&2
    return 1
  fi
  docker exec -it "$1" sh
}

dbash() {
  if [ $# -lt 1 ] || [ -z "${1:-}" ]; then
    printf 'usage: dbash <container>\n' >&2
    return 1
  fi
  docker exec -it "$1" bash 2>/dev/null || docker exec -it "$1" sh
}

dins() {
  if [ $# -lt 1 ] || [ -z "${1:-}" ]; then
    printf 'usage: dins <container>\n' >&2
    return 1
  fi
  docker inspect "$1"
}
